name: "Create release"

on:
  push:
    tags:
      - "v*"

jobs:
  release-windows-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "Build VFPL for Linux"
        run: "cargo build --release --target x86_64-unknown-linux-gnu --verbose"
      - name: Install MinGW
        uses: egor-tensin/setup-mingw@v2
      - name: "Add Windows Target"
        run: rustup target add x86_64-pc-windows-gnu
      - name: "Build VFPL for Windows"
        run: "cargo build --release --target x86_64-pc-windows-gnu --verbose"
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            LICENSE
            target/x86_64-unknown-linux-gnu/release/vfpl
            target/x86_64-pc-windows-gnu/release/vfpl.exe
