name: "Create release"

on:
  push:
    tags:
      - "v*"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: cargo test --verbose --all

  create-release:
    runs-on: ubuntu-latest
    needs: [run-tests]
    outputs:
      upload_url: ${{ steps.create-release-step.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create-release-step
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: |
            LICENSE

  release-windows:
    runs-on: windows-latest
    needs: [create-release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build VFPL for Windows
        run: cargo build --release --verbose
      - name: Upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/release/vfpl.exe
          asset_name: vfpl_windows.exe
          asset_content_type: application/octet-stream

  release-linux:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build VFPL for Linux
        run: cargo build --release --verbose
      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: target/release/vfpl
          asset_name: vfpl_linux
          asset_content_type: application/octet-stream
